ehealthy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('healthApp.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

healthApp/urls.py
from django.urls import path

from . import views, PredictionViews, PostViews

app_name = 'healthApp'
urlpatterns = [
    path('', views.home, name='home'),

    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),

    path('user/profile/', views.user_profile, name='user_profile'),
    path('user/edit_save/<int:id>', views.user_edit_save, name='user_edit_save'),
    path('user/my_posts/<int:id>', views.list_post_by_user_id, name='list_post_by_user_id'),

    path('post/detail/<int:id>', PostViews.post_detail, name='post_detail'),
    path('post/create/', PostViews.post_create, name='post_create'),
    path('post/create_save/', PostViews.post_create_save, name='post_create_save'),
    path('post/edit_save/<int:id>', PostViews.post_edit_save, name='post_edit_save'),
    path('post/delete/<int:id>', PostViews.post_delete, name='post_delete'),

    path('predict/heart/', PredictionViews.heart, name='heart'),
    path('predict/heart_predict/', PredictionViews.heart_predict, name='heart_predict'),
    path('predict/kidney/', PredictionViews.kidney, name='kidney'),
    path('predict/kidney_predict/', PredictionViews.kidney_predict, name='kidney_predict'),
    path('predict/diabetes/', PredictionViews.diabetes, name='diabetes'),
    path('predict/diabetes_predict/', PredictionViews.diabetes_predict, name='diabetes_predict'),
    path('predict/liver/', PredictionViews.liver, name='liver'),
    path('predict/liver_predict/', PredictionViews.liver_predict, name='liver_predict'),
    path('predict/cancer/', PredictionViews.cancer, name='cancer'),
    path('predict/cancer_predict/', PredictionViews.cancer_predict, name='cancer_predict'),
    path('predict/result/', PredictionViews.result, name='result'),
]

templates/prediction/cancer.html
{% extends 'base.html' %}

{% block main_content %}

    {% load static %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Bệnh ung thư</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Trang chủ</a></li>
                    <li class="breadcrumb-item">Dự đoán</li>
                    <li class="breadcrumb-item active">Bệnh ung thư</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-md-8" style="float:none;margin:auto;">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Vui lòng điền thông tin phía dưới</h5>

                            <form action="{% url 'healthApp:cancer_predict' %}" method="POST">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="concave points_mean" class="col-sm-4 col-form-label">Mean of the Concave
                                        Points</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step=0.01 id="concave_points_mean"
                                               name="concave_points_mean" required="required"
                                               placeholder="Mean of the Concave Points">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="area_mean" class="col-sm-4 col-form-label">Mean of the Area</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step="any" id="area_mean"
                                               name="area_mean"
                                               required="required" placeholder="Mean of the Area">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="radius_mean" class="col-sm-4 col-form-label">Mean of the Radius</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="radius_mean" name="radius_mean"
                                               required="required"
                                               placeholder="Mean of the radius">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="perimeter_mean" class="col-sm-4 col-form-label">Mean of the
                                        Perimeters</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="perimeter_mean"
                                               name="perimeter_mean"
                                               required="required" placeholder="Mean of the Parameter">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="concavity_mean" class="col-sm-4 col-form-label">Mean of the
                                        Concavity</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="concavity_mean"
                                               name="concavity_mean"
                                               required="required" placeholder="Mean of the concavity">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-4"></div>
                                    <div class="col-sm-8">
                                        <button type="submit" class="btn btn-primary">Predict</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock main_content %}

templates/prediction/diabetes.html
{% extends 'base.html' %}

{% block main_content %}

    {% load static %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Bệnh tiểu đường</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Trang chủ</a></li>
                    <li class="breadcrumb-item">Dự đoán</li>
                    <li class="breadcrumb-item active">Bệnh tiểu đường</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-md-8" style="float:none;margin:auto;">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Vui lòng điền thông tin phía dưới</h5>

                            <form action="{% url 'healthApp:diabetes_predict' %}" method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="Pregnancies" class="col-sm-4 col-form-label">No. of Pregnencies</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Pregnancies" name="Pregnancies"
                                               required="required" placeholder="No. of Pregnencies">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Glucose" class="col-sm-4 col-form-label">Glucose Level</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step="any" id="Glucose" name="Glucose"
                                               required="required" placeholder="Glucose Level">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="radius_mean" class="col-sm-4 col-form-label">Mean of the Radius</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="radius_mean" name="radius_mean"
                                               required="required"
                                               placeholder="Mean of the radius">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="BloodPressure" class="col-sm-4 col-form-label">Current Blood
                                        Pressure</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="BloodPressure"
                                               name="BloodPressure" required="required"
                                               placeholder="Current Blood Pressure">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="BMI" class="col-sm-4 col-form-label">Enter the Body Mass Index</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="BMI" name="BMI"
                                               required="required" placeholder="Body Mass Index">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="DiabetesPedigreeFunction" class="col-sm-4 col-form-label">Diabetes
                                        Pedigree Function</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="DiabetesPedigreeFunction"
                                               name="DiabetesPedigreeFunction" required="required"
                                               placeholder="Diabetes Pedigree Function">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Age" class="col-sm-4 col-form-label">Age</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Age" name="Age"
                                               required="required" placeholder="Age">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-4"></div>
                                    <div class="col-sm-8">
                                        <button type="submit" class="btn btn-primary">Predict</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock main_content %}

templates/prediction/heart.html
{% extends 'base.html' %}

{% block main_content %}

    {% load static %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Bệnh tim</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Trang chủ</a></li>
                    <li class="breadcrumb-item">Dự đoán</li>
                    <li class="breadcrumb-item active">Bệnh tim</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-md-8" style="float:none;margin:auto;">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Vui lòng điền thông tin phía dưới</h5>

                            <form action="{% url 'healthApp:heart_predict' %}" method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="cp" class="col-sm-4 col-form-label">Chest Pain Type</label>
                                    <div class="col-sm-8">
                                        <select class="form-control" id="cp" name="cp" required="required"
                                                placeholder="Chest Pain Type">
                                            <option value="1">Typical Angina</option>
                                            <option value="2">Atypical Angina</option>
                                            <option value="3">Non-Anginal Pain</option>
                                            <option value="4">Asymptomatic</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Glucose" class="col-sm-4 col-form-label">Glucose Level</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step="any" id="Glucose" name="Glucose"
                                               required="required" placeholder="Glucose Level">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="trestbps" class="col-sm-4 col-form-label">Resting Blood Pressure (in mm
                                        Hg)</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="trestbps" name="trestbps"
                                               required="required" placeholder="Resting Blood Pressure">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="chol" class="col-sm-4 col-form-label">Serum Cholestoral in mg/dl</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step="any" id="chol" name="chol"
                                               required="required" placeholder="Serum Cholestoral">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="fbs" class="col-sm-4 col-form-label">Fasting Blood Sugar</label>
                                    <div class="col-sm-8">
                                        <select class="form-control" id="fbs" name="fbs" required="required"
                                                placeholder="Fasting Blood Sugar">
                                            <option value="0">Fasting Blood Sugar < 120 mg/dl</option>
                                            <option value="1">Fasting Blood Sugar > 120 mg/dl</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="restecg" class="col-sm-4 col-form-label">Resting Electro-cardiographic
                                        Result</label>
                                    <div class="col-sm-8">
                                        <select class="form-control" type="number" id="restecg" name="restecg"
                                                required="required" placeholder="Resting Electro-cardiographic Result">
                                            <option value="0">Normal</option>
                                            <option value="1">having ST-T wave abnormality</option>
                                            <option value="2">showing probable or definite left ventricular
                                                hypertrophy
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="thalach" class="col-sm-4 col-form-label">Maximum Heart Rate
                                        Achieved</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" id="thalach" name="thalach" required="required">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="exang" class="col-sm-4 col-form-label">Exercise Induced Angina</label>
                                    <div class="col-sm-8">
                                        <select class="form-control" id="exang" name="exang" required="required">
                                            <option value="1">Yes</option>
                                            <option value="0">No</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-4"></div>
                                    <div class="col-sm-8">
                                        <button type="submit" class="btn btn-primary">Predict</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock main_content %}

templates/prediction/kidney.html
{% extends 'base.html' %}

{% block main_content %}

    {% load static %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Bệnh thận</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Trang chủ</a></li>
                    <li class="breadcrumb-item">Dự đoán</li>
                    <li class="breadcrumb-item active">Bệnh thận</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-md-8" style="float:none;margin:auto;">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Vui lòng điền thông tin phía dưới</h5>

                            <form action="{% url 'healthApp:kidney_predict' %}" method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="bp" class="col-sm-4 col-form-label">Blood Pressure</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="bp" name="bp" required="required"
                                               placeholder="Blood Pressure">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="sg" class="col-sm-4 col-form-label">Specific Gravity</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step="any" id="sg" name="sg"
                                               required="required" placeholder="Specific Gravity">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="al" class="col-sm-4 col-form-label">Albumin</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="al" name="al" required="required"
                                               placeholder="Albumin">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="su" class="col-sm-4 col-form-label">Blood Sugar Level</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="su" name="su" required="required"
                                               placeholder="Blood Sugar Level">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="rbc" class="col-sm-4 col-form-label">Red Blood Cells Count</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="rbc" name="rbc"
                                               required="required" placeholder="Red Blood Cells Count">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="pc" class="col-sm-4 col-form-label">Pus Cell Count</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="pc" name="pc" required="required"
                                               placeholder="Pus Cell Count">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="pcc" class="col-sm-4 col-form-label">Pus Cell Clumps</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="pcc" name="pcc"
                                               required="required" placeholder="Pus Cell Clumps">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-4"></div>
                                    <div class="col-sm-8">
                                        <button type="submit" class="btn btn-primary">Predict</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock main_content %}

templates/prediction/liver.html
{% extends 'base.html' %}

{% block main_content %}

    {% load static %}
    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Bệnh gan</h1>
            <nav>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="/home">Trang chủ</a></li>
                    <li class="breadcrumb-item">Dự đoán</li>
                    <li class="breadcrumb-item active">Bệnh gan</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section class="section">
            <div class="row">
                <div class="col-md-8" style="float:none;margin:auto;">

                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Vui lòng điền thông tin phía dưới</h5>

                            <form action="{% url 'healthApp:liver_predict' %}" method="post">
                                {% csrf_token %}
                                <div class="row mb-3">
                                    <label for="Total Bilirubin" class="col-sm-4 col-form-label">Total Bilirubin</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Total_Bilirubin"
                                               name="Total_Bilirubin" required="required"
                                               placeholder="Enter the Total Bilirubin">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Direct_Bilirubin" class="col-sm-4 col-form-label">Direct
                                        Bilirubin</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" step="any" id="Direct_Bilirubin"
                                               name="Direct_Bilirubin" required="required"
                                               placeholder="Enter the Direct_Bilirubin">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Alkaline_Phosphotase" class="col-sm-4 col-form-label">Alkaline
                                        Phosphotase</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Alkaline_Phosphotase"
                                               name="Alkaline_Phosphotase" required="required"
                                               placeholder="Enter the Alkaline Phosphotase">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Alamine_Aminotransferase" class="col-sm-4 col-form-label">Alamine
                                        Aminotransferase</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Alamine_Aminotransferase"
                                               name="Alamine_Aminotransferase" required="required"
                                               placeholder="Enter the Alamine Aminotransferase">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Total_Protiens" class="col-sm-4 col-form-label">Total Protiens</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Total_Protiens"
                                               name="Total_Protiens" required="required"
                                               placeholder="Enter the Total Protiens">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Albumin" class="col-sm-4 col-form-label">Albumin</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Albumin" name="Albumin"
                                               required="required" placeholder="Enter the Albumin">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <label for="Albumin_and_Globulin_Ratio" class="col-sm-4 col-form-label">Albumin and
                                        Globulin Ratio</label>
                                    <div class="col-sm-8">
                                        <input class="form-control" type="number" id="Albumin_and_Globulin_Ratio"
                                               name="Albumin_and_Globulin_Ratio" required="required"
                                               placeholder="Enter the Albumin and Globulin Ratio">
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-sm-4"></div>
                                    <div class="col-sm-8">
                                        <button type="submit" class="btn btn-primary">Predict</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock main_content %}